"""Generated by scripts/generate-classic-proposals.py. Do not edit."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator
from pydantic import RootModel, model_validator

PROPOSAL_SCHEMA = json.loads(Path(__file__).with_name("classic-proposal.schema.json").read_text("utf-8"))


class ClassicProposalResponse(RootModel[dict[str, Any]]):
    """The generated discriminated response model for Classic roles."""

    @model_validator(mode="after")
    def validate_proposal(self) -> ClassicProposalResponse:
        errors = list(Draft202012Validator(PROPOSAL_SCHEMA).iter_errors(self.root))
        if errors:
            raise ValueError(errors[0].message)
        return self

    @classmethod
    def model_json_schema(cls, **kwargs: Any) -> dict[str, Any]:
        return PROPOSAL_SCHEMA
