"""Generate the agent model and parser fixtures from the Classic registry."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "daemon/src"))

from core.variants.classic.proposals import (
    parser_fixtures,
    proposal_schema,
)


def outputs() -> dict[Path, str]:
    schema = json.dumps(proposal_schema(), sort_keys=True, indent=2)
    model = '''"""Generated by scripts/generate-classic-proposals.py. Do not edit."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator
from pydantic import RootModel, model_validator

PROPOSAL_SCHEMA = json.loads(Path(__file__).with_name("classic-proposal.schema.json").read_text("utf-8"))


class ClassicProposalResponse(RootModel[dict[str, Any]]):
    """The generated discriminated response model for Classic roles."""

    @model_validator(mode="after")
    def validate_proposal(self) -> ClassicProposalResponse:
        errors = list(Draft202012Validator(PROPOSAL_SCHEMA).iter_errors(self.root))
        if errors:
            raise ValueError(errors[0].message)
        return self

    @classmethod
    def model_json_schema(cls, **kwargs: Any) -> dict[str, Any]:
        return PROPOSAL_SCHEMA
'''
    return {
        ROOT / "agent/bmas_protocol/proposals.py": model,
        ROOT / "agent/bmas_protocol/classic-proposal.schema.json": schema + "\n",
        ROOT / "conformance/proposal_fixtures/classic-proposals.json": json.dumps(
            {"reason": "The Classic registry defines the generated parser cases.",
             "cases": parser_fixtures()}, indent=2, sort_keys=True) + "\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                print(f"Stale generated Classic contract: {path.relative_to(ROOT)}")
                return 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
